#!/bin/bash

CC="clang"

CFLAGS="-Wall -Wextra -std=c2x -pedantic"

# make "d$1" >> /dev/null

if [[ $# -ne 2 ]]; then
  echo "Not enough arguments";
  exit 1;
fi

day_dir="./day$1"
make_file="Makefile"
out_file="d${1}p${2}.out"
c_file="d${1}p${2}.c"
input_file="day${1}input.txt"

if [[ -f "${day_dir}/${make_file}" ]]; then
  cd "$day_dir" || exit

  make >> /dev/null
  
  "./$out_file" "./$input_file"

  exit 0
fi

if [[ ! -f "$day_dir/$make_file" && ! -f "$day_dir/$c_file" ]]; then
  echo "$day_dir/$c_file does not exist!"
  exit 1
fi

if [[ ! -f "$day_dir/$input_file" ]]; then
  echo "Input file ${day_dir}/${input_file} does not exist!"
  exit 1
fi

if [[ ! -f "$day_dir/$make_file" ]]; then
  $CC $CFLAGS -o $out_file $c_file 
fi

"./$day_dir/$out_file" "./$day_dir/$input_file"
